backend:
  name: github
  repo: https://github.com/ishan501/sveltekit-test
  branch: main  # Change to your Git branch if different

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "product-list"
    label: "Product List"
    file: "content/products.json"
    description: "Manage the list of all products"
    format: "json"
    fields:
      - label: "Products"
        name: "products"
        widget: "list"
        fields:
          - { name: "id", label: "ID", widget: "number" }
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - { name: "image", label: "Image", widget: "image" }
          - { name: "ctaText", label: "CTA Text", widget: "string" }
          - { name: "ctaLink", label: "CTA Link", widget: "string" }

  - name: "products"
    label: "Products (Individual Pages)"
    folder: "content/products"
    create: true
    slug: "{{title | slugify}}"  # Creates file names like `jupitermeet.json`
    format: "json"
    fields:
      - label: "Hero Section"
        name: "hero"
        widget: "object"
        fields:
          - { name: "title", label: "Product Title", widget: "string" }
          - { name: "description", label: "Product Description", widget: "text" }
          - { name: "image", label: "Hero Image", widget: "image" }
          - { name: "primary-color", label: "Primary Color", widget: "color" }

          - label: "Call-to-Actions (CTAs)"
            name: "ctas"
            widget: "list"
            fields:
              - { name: "id", label: "CTA ID", widget: "number" }
              - { name: "title", label: "CTA Title", widget: "string" }
              - { name: "link", label: "CTA Link", widget: "string" }
              - { name: "isPrimary", label: "Primary Button?", widget: "boolean" }
